In [14]:
import numpy as np
from characteristic_time import compute_characteristic_time
from feedback_graph import FeedbackGraph, Graph
from reward_model import GaussianRewardModel

mu = [0.9, 0.5, 0.2 , 0.1]
G = np.array([
    [0, 0.1, 0.1, 0],
    [0.3, 0, 0, 0],
    [0., 0.2, 0, 0.3],
    [0., 0.1, 0.2, 0.]
])
rm = GaussianRewardModel(mu)
graph = Graph(G)
fg = FeedbackGraph(reward_model=rm, graph=graph)


compute_characteristic_time(fg)



(218.18185731332258,
 array([1.98387007e-09, 4.27471668e-01, 4.63015549e-01, 1.09512780e-01]),
 array([0.1282415 , 0.10355439, 0.02190256, 0.13890466]),
 array([218.18185731]))

In [21]:
12/np.min(np.minimum([0.1, 0.1, 0.3], 0.3)* ( fg.reward_model.gaps[1:] ** 2))

np.float64(749.9999999999998)

In [15]:
gaps = rm.gaps.copy() ** 2
gaps[0] = gaps[1]

x = ( 1 / gaps)
x = x / x.sum()
x

array([0.38811881, 0.38811881, 0.12673267, 0.0970297 ])