In [4]:
import numpy as np
from environment import run_experiment
from baifg.model.feedback_graph import FeedbackGraph
from baifg.model.reward_model import GaussianRewardModel, RewardType
from baifg.algorithms.eps_greedy import EpsilonGreedy, EpsilonGreedyParameters
from baifg.algorithms.base.graph_estimator import GraphEstimator
from baifg.utils.graphs import make_loopless_clique

seed = 0
p = 0.5
K = 5
informed = False
mu = np.linspace(0, 1, K)
fg = make_loopless_clique(p, mu)
algo = EpsilonGreedy(
    GraphEstimator.optimistic_graph(K, informed=informed, known=False),
    fg.reward_model.reward_type,
    delta=1e-3,
    parameters=EpsilonGreedyParameters(exp_rate=0.7),)

run_experiment(fg=fg, algo=algo, seed=seed)

print(fg.graph.G)

---------- Time 1 -------------
[1. 0. 0. 0. 0.]
[ 1.          1.         -0.25587654  1.          1.83081191]
[[1. 1. 2. 1. 2.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
-------------------
---------- Time 2 -------------
[2. 0. 0. 0. 0.]
[ 1.          1.         -0.48331558  1.          1.30712542]
[[0.5 0.5 1.5 0.5 1.5]
 [1.  1.  1.  1.  1. ]
 [1.  1.  1.  1.  1. ]
 [1.  1.  1.  1.  1. ]
 [1.  1.  1.  1.  1. ]]
-------------------
---------- Time 3 -------------
[2. 0. 0. 1. 0.]
[-0.4157447   1.          0.11549004  1.          1.30712542]
[[0.5 0.5 1.5 0.5 1.5]
 [1.  1.  1.  1.  1. ]
 [1.  1.  1.  1.  1. ]
 [2.  1.  2.  1.  1. ]
 [1.  1.  1.  1.  1. ]]
-------------------
---------- Time 4 -------------
[3. 0. 0. 1. 0.]
[-0.4157447   1.          0.30285686  1.92966077  1.30712542]
[[0.33333333 0.33333333 1.33333333 0.66666667 1.        ]
 [1.         1.         1.         1.         1.        ]
 [1.         1.         1.         1.         1.        ]